version: "3"

services:
  postigis:
    image: "mdillon/postgis:latest"
    ports:
      - "5432:5432"
    volumes:
      - postigis:/var/lib/postgresql/data

  app:
    depends_on:
      - "postigis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebittinder
      - gems:/gems

volumes:
  postigis:
  gems:
