default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: ubuntu
  password: Lucasdfg07
  # host: postgres
  # user: postgres
  # password: Lucasdfg07

development:
  <<: *default
  database: onebitinder_api_development

test:
  <<: *default
  database: onebitinder_api_test

production:
  <<: *default
  database: onebitinder_api_production
  username: onebitinder_api
  password: <%= ENV['ONEBITINDER_API_DATABASE_PASSWORD'] %>
